# Generated by Django 5.1.1 on 2024-09-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('duracion', models.DurationField()),
                ('cantidad_asistentes', models.IntegerField()),
                ('horario_deseado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario_disponibilidad', models.CharField(max_length=50)),
                ('capacidad_maxima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='server.reunion')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='server.sala')),
            ],
        ),
    ]
